# Generated by Django 2.2.17 on 2021-03-22 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matemaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('members', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(default='no description', max_length=128)),
                ('views', models.IntegerField(default=0)),
                ('members', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='date created')),
                ('creator', models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matemaker.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='intersts',
            field=models.ManyToManyField(to='matemaker.Interest'),
        ),
    ]
