# Generated by Django 2.2.17 on 2021-03-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matemaker', '0002_auto_20210322_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date created'),
        ),
    ]
