# Generated by Django 2.2.17 on 2021-03-22 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matemaker', '0003_auto_20210322_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='creator',
        ),
    ]
