# Generated by Django 2.2.17 on 2021-04-01 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matemaker', '0004_remove_interest_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name_plural': 'Genres'},
        ),
    ]
