# Generated by Django 2.2.17 on 2021-04-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matemaker', '0005_auto_20210401_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='PLEASE FILL', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interest',
            name='slug',
            field=models.SlugField(default='PLEASE FILL', unique=True),
            preserve_default=False,
        ),
    ]
