# Generated by Django 2.2.17 on 2021-04-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matemaker', '0009_auto_20210404_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='intersts',
            field=models.ManyToManyField(blank=True, to='matemaker.Interest'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='defaults/default_pp.jpg', upload_to='profile_images'),
        ),
    ]
