# Generated by Django 2.2.17 on 2021-04-05 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matemaker', '0010_auto_20210405_0405'),
        ('matemaker', '0010_auto_20210405_0231'),
    ]

    operations = [
    ]
