# Generated by Django 2.2.17 on 2021-04-05 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matemaker', '0011_merge_20210405_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='Hello world!', max_length=128)),
                ('date', models.DateTimeField(null=True, verbose_name='date created')),
                ('likes', models.IntegerField(default=0)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matemaker.Interest')),
                ('poster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
